In [1]:
import pandas as pd 
import numpy as np

In [2]:
train_df = pd.read_csv("Train_aBjfeNk.csv")
train_df.head()

ID  Gender Ever_Married  Age Graduated     Profession  Work_Experience  \
0  462809    Male           No   22        No     Healthcare              1.0   
1  462643  Female          Yes   38       Yes       Engineer              NaN   
2  466315  Female          Yes   67       Yes       Engineer              1.0   
3  461735    Male          Yes   67       Yes         Lawyer              0.0   
4  462669  Female          Yes   40       Yes  Entertainment              NaN   

  Spending_Score  Family_Size  Var_1 Segmentation  
0            Low          4.0  Cat_4            D  
1        Average          3.0  Cat_4            A  
2            Low          1.0  Cat_6            B  
3           High          2.0  Cat_6            B  
4           High          6.0  Cat_6            A

In [3]:
test_df = pd.read_csv("Test_LqhgPWU.csv")
test_df.head()

ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0  458989  Female          Yes   36       Yes    Engineer              0.0   
1  458994    Male          Yes   37       Yes  Healthcare              8.0   
2  458996  Female          Yes   69        No         NaN              0.0   
3  459000    Male          Yes   59        No   Executive             11.0   
4  459001  Female           No   19        No   Marketing              NaN   

  Spending_Score  Family_Size  Var_1  
0            Low          1.0  Cat_6  
1        Average          4.0  Cat_6  
2            Low          1.0  Cat_6  
3           High          2.0  Cat_6  
4            Low          4.0  Cat_6

In [4]:
train_df.isnull().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [5]:
test_df.isnull().sum()

ID                   0
Gender               0
Ever_Married        50
Age                  0
Graduated           24
Profession          38
Work_Experience    269
Spending_Score       0
Family_Size        113
Var_1               32
dtype: int64

In [6]:
dupes = train_df.duplicated()
sum(dupes)

0

In [7]:
## unique items
print("Gender")
print(train_df.Gender.unique())
print("")
print("Ever_married")
print(train_df.Ever_Married.unique())
print("")
print("Graduated")
print(train_df.Graduated.unique())
print("")
print("Profession")
print(train_df.Profession.unique())
print("")
print("Work_Experience")
print(train_df.Work_Experience.unique())
print("")
print("Spending_Score")
print(train_df.Spending_Score.unique())
print("")
print("Family_size")
print(train_df.Family_Size.unique())
print("")
print("Anonymised Category for the customer")
print(train_df.Var_1.unique())
print("")
print("Segmentation")
print(train_df.Segmentation.unique())

Gender
['Male' 'Female']

Ever_married
['No' 'Yes' nan]

Graduated
['No' 'Yes' nan]

Profession
['Healthcare' 'Engineer' 'Lawyer' 'Entertainment' 'Artist' 'Executive'
 'Doctor' 'Homemaker' 'Marketing' nan]

Work_Experience
[ 1. nan  0.  4.  9. 12.  3. 13.  5.  8. 14.  7.  2.  6. 10. 11.]

Spending_Score
['Low' 'Average' 'High']

Family_size
[ 4.  3.  1.  2.  6. nan  5.  8.  7.  9.]

Anonymised Category for the customer
['Cat_4' 'Cat_6' 'Cat_7' 'Cat_3' 'Cat_1' 'Cat_2' nan 'Cat_5']

Segmentation
['D' 'A' 'B' 'C']


In [8]:
train_data = train_df.copy()

In [9]:
train_data['Ever_Married'].fillna('None', inplace=True)
train_data['Graduated'].fillna('None', inplace=True)
train_data['Profession'].fillna('None', inplace=True)
train_data['Var_1'].fillna('None', inplace=True)

In [10]:
train_data["Work_Experience"].fillna(train_data["Work_Experience"].mean(), inplace=True)
train_data["Family_Size"].fillna(train_data["Family_Size"].mean(), inplace=True)

In [11]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 

In [12]:
train_data['Gender']= label_encoder.fit_transform(train_data['Gender'])
train_data['Ever_Married']= label_encoder.fit_transform(train_data['Ever_Married'])
train_data['Graduated']= label_encoder.fit_transform(train_data['Graduated'])
train_data['Profession']= label_encoder.fit_transform(train_data['Profession'])
train_data['Spending_Score']= label_encoder.fit_transform(train_data['Spending_Score'])
train_data['Var_1']= label_encoder.fit_transform(train_data['Var_1'])

In [13]:
label_target = preprocessing.LabelEncoder() 
train_data['Segmentation']= label_target.fit_transform(train_data['Segmentation'])

In [14]:
print("Gender")
print(train_data.Gender.unique())
print("")
print("Ever_married")
print(train_data.Ever_Married.unique())
print("")
print("Graduated")
print(train_data.Graduated.unique())
print("")
print("Profession")
print(train_data.Profession.unique())
print("")
print("Work_Experience")
print(train_data.Work_Experience.unique())
print("")
print("Spending_Score")
print(train_df.Spending_Score.unique())
print("")
print("Family_size")
print(train_data.Family_Size.unique())
print("")
print("Anonymised Category for the customer")
print(train_data.Var_1.unique())
print("")
print("Segmentation")
print(train_data.Segmentation.unique())

Gender
[1 0]

Ever_married
[0 2 1]

Graduated
[0 2 1]

Profession
[5 2 7 3 0 4 1 6 8 9]

Work_Experience
[ 1.          2.64166321  0.          4.          9.         12.
  3.         13.          5.          8.         14.          7.
  2.          6.         10.         11.        ]

Spending_Score
['Low' 'Average' 'High']

Family_size
[4.         3.         1.         2.         6.         2.85012285
 5.         8.         7.         9.        ]

Anonymised Category for the customer
[3 5 6 2 0 1 7 4]

Segmentation
[3 0 1 2]


In [15]:
test_data = test_df.copy()

In [16]:
test_data['Ever_Married'].fillna('None', inplace=True)
test_data['Graduated'].fillna('None', inplace=True)
test_data['Profession'].fillna('None', inplace=True)
test_data['Var_1'].fillna('None', inplace=True)

In [17]:
test_data["Work_Experience"].fillna(test_data["Work_Experience"].mean(), inplace=True)
test_data["Family_Size"].fillna(test_data["Family_Size"].mean(), inplace=True)

In [18]:
test_data['Gender']= label_encoder.fit_transform(test_data['Gender'])
test_data['Ever_Married']= label_encoder.fit_transform(test_data['Ever_Married'])
test_data['Graduated']= label_encoder.fit_transform(test_data['Graduated'])
test_data['Profession']= label_encoder.fit_transform(test_data['Profession'])
test_data['Spending_Score']= label_encoder.fit_transform(test_data['Spending_Score'])
test_data['Var_1']= label_encoder.fit_transform(test_data['Var_1'])

In [19]:
print("Gender")
print(test_data.Gender.unique())
print("")
print("Ever_married")
print(test_data.Ever_Married.unique())
print("")
print("Graduated")
print(test_data.Graduated.unique())
print("")
print("Profession")
print(test_data.Profession.unique())
print("")
print("Work_Experience")
print(test_data.Work_Experience.unique())
print("")
print("Spending_Score")
print(test_data.Spending_Score.unique())
print("")
print("Family_size")
print(test_data.Family_Size.unique())
print("")
print("Anonymised Category for the customer")
print(test_data.Var_1.unique())

Gender
[0 1]

Ever_married
[2 0 1]

Graduated
[2 0 1]

Profession
[2 5 9 4 8 1 0 7 3 6]

Work_Experience
[ 0.          8.         11.          2.55258694  5.          1.
  2.          9.          3.          6.          7.          4.
 13.         10.         12.         14.        ]

Spending_Score
[2 0 1]

Family_size
[1.         4.         2.         5.         3.         6.
 2.82537788 8.         7.         9.        ]

Anonymised Category for the customer
[5 3 2 7 0 1 4 6]


In [20]:
X_train = train_data.drop(["ID","Segmentation"] , axis=1)
y_train = train_data.pop("Segmentation")

In [21]:
X_test = test_data.drop(["ID"] , axis=1)

## Linear svc

In [22]:
from sklearn.svm import LinearSVC
svc = LinearSVC(C=100)
svc = svc.fit(X_train,y_train)

C:\Users\lokesh duvvuru\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [23]:
print(svc.score(X_train, y_train))

0.3675012394645513


In [24]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
clf = OneVsRestClassifier(SVC()).fit(X_train, y_train)

C:\Users\lokesh duvvuru\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\lokesh duvvuru\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\lokesh duvvuru\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\lokesh duvvuru\Anaconda3\lib\site-packages\

In [25]:
print(clf.score(X_train, y_train))

0.7394645513138324


In [26]:
from sklearn.ensemble import ExtraTreesClassifier
clf = OneVsRestClassifier(ExtraTreesClassifier(n_estimators=100, random_state=0)).fit(X_train, y_train)

In [27]:
print(clf.score(X_train, y_train))

0.960213187902826


In [28]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
clf = clf.fit(X_train, y_train)

C:\Users\lokesh duvvuru\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [29]:
print(clf.score(X_train, y_train))

0.939514129895885


In [30]:
y_pred = clf.predict(X_test)

In [31]:
A = pd.DataFrame(data=y_pred ,columns=["Segmentation"])

In [32]:
A['Segmentation']= label_target.inverse_transform(A['Segmentation'])

In [33]:
submission = pd.read_csv("sample_submission_wyi0h0z.csv")
S = submission.drop(["Segmentation"] , axis=1)
S

ID
0     458989
1     458994
2     458996
3     459000
4     459001
...      ...
2622  467954
2623  467958
2624  467960
2625  467961
2626  467968

[2627 rows x 1 columns]

In [34]:
Sub = pd.merge(S , A, on=None, left_index= True,
    right_index=True)

In [35]:
Sub

ID Segmentation
0     458989            B
1     458994            C
2     458996            A
3     459000            C
4     459001            D
...      ...          ...
2622  467954            D
2623  467958            B
2624  467960            B
2625  467961            C
2626  467968            D

[2627 rows x 2 columns]

In [36]:
Sub.to_csv('RFC1.csv',index = False)

In [37]:
from sklearn.ensemble import BaggingClassifier
dff = ExtraTreesClassifier(n_estimators=500, random_state=0)
bgcl = BaggingClassifier(base_estimator=dff, n_estimators=50,random_state=1)
bgcl = bgcl.fit(X_train, y_train)

In [38]:
print(bgcl.score(X_train , y_train))

0.9599652949925632


In [39]:
y_pred = bgcl.predict(X_test)

In [40]:
A = pd.DataFrame(data=y_pred ,columns=["Segmentation"])

In [41]:
A['Segmentation']= label_target.inverse_transform(A['Segmentation'])

In [42]:
Sub = pd.merge(S , A, on=None, left_index= True,
    right_index=True)

In [43]:
Sub.to_csv('BGETF.csv',index = False)

## LGBM

In [57]:
import lightgbm as lgb
lgb = lgb.LGBMClassifier(n_estimators=5000,)
lgb.fit(X_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=5000, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [58]:
print(lgb.score(X_train , y_train))

0.9599652949925632


In [59]:
y_pred = lgb.predict(X_test)

In [60]:
A = pd.DataFrame(data=y_pred ,columns=["Segmentation"])

In [61]:
A['Segmentation']= label_target.inverse_transform(A['Segmentation'])

In [62]:
A

Segmentation
0               B
1               C
2               D
3               C
4               D
...           ...
2622            D
2623            B
2624            A
2625            C
2626            D

[2627 rows x 1 columns]

In [63]:
Sub = pd.merge(S , A, on=None, left_index= True,
    right_index=True)

In [64]:
Sub.to_csv('lgb1.csv',index = False)